### ISSUE TITLE
Главное меню: Неверное название пункта меню

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#11]
1. Сравнить название пунктов главного меню с требованиями

### Получено:
Пункты меню : "Проекты", "Задачи", "Персоны"

### Ожидаемо:
Пункты меню : "Проекты", "Задачи", "Сотрудники"

См. Требования п.1 Главное меню
![Неверное название Списка задач](https://user-images.githubusercontent.com/91781472/139140285-808ba36b-2857-4644-af52-885cef590c42.jpg)

**Comment by Svkarpova** [comment]
Данный дефект не актуален. В требованиях в п. Главное меню, написано:
- Проекты: Отображается форма “Список проектов”
- Задачи: Отображается форма “Список задач”
- Персоны: Отображается форма “Список сотрудников”

Т.е. при нажатии на "Проекты" отображается форма "Список проектов" и т.д.
