### ISSUE TITLE
Форма ввода/редактирования сотрудника: Несоответствие максимального кол-ва символов поля Должность

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#12]
1. Перейти в [Cписок сотрудников]
2. Перейти в [Форма ввода сотрудника]
3. Выполнить валидацию поля [Должность] на максимальное кол-во символов

### Получено:
Максимальное количество символов 30

### Ожидаемо:
Максимальное количество символов 50

См. Требования п.7 Поле Должность

**Comment by Svkarpova** [comment]
- Из заголовка непонятно в чем ошибка: нужно точно написать какое допустимое кол-во символов (максимальное, минимальное, среднее?) 
- В шагах, в полученном и ожидаемом результате, тоже исправить на точное кол-во допустимых символов
