### ISSUE TITLE
Форма ввода/редактирования сотрудника: Неверное максимальное кол-во символов в справке для поля "Должность"

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#14]
1. Перейти в [Cписок сотрудников]
2. Перейти в [Форма вода сотрудника]
3. Выполнить проверку содержание справки для поля [Должность]

### Получено:
Сообщение: "...Количество символов: от 2 до 30"

### Ожидаемо:
Сообщение: "...Количество символов: от 2 до 50"

См. Требования п.7 Поле Должность
![Qulix№6](https://user-images.githubusercontent.com/91781472/139142668-c3594016-1bda-488a-8d33-e2ec26e2e9e7.png)

**Comment by Svkarpova** [comment]
В заголовке нужно более конкретно написать, в чем дефект, например "Неверное максимальное кол-во символов в справке для поля "Должность""
