### ISSUE TITLE
Форма ввода/редактирования сотрудника: Недопустимость сохранения валидного символа '\' в поле Должность

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#15]
1. Перейти в [Cписок сотрудников]
2. Перейти в [Форма ввода сотрудника]
3. Заполнить поле [Должность] валидным кол-вом знаков включая символ "\/"

### Получено:
Символ "/\" недопустим

### Ожидаемо:
Символ "/\" допустим

См. Требования п.7 Поле Должность
![Qulix№3](https://user-images.githubusercontent.com/91781472/139143556-6f3cf244-db8e-44d2-af39-2510f45c9c70.png)

**Comment by Svkarpova** [comment]
В описании не указан допустимый символ
