### ISSUE TITLE
Форма ввода/редактирования сотрудника: Сохранение сотрудника с невалидным полем Должность

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#16]
1. Перейти в [Cписок сотрудников]
2. Перейти в [Форма ввода сотрудника]
3. Заполнить все поля формы, кроме поля [Должность]
4. Заполнить поле [Должность] несколькими символами пробела
5. Сохранить запись

### Получено:
Сотрудник создан

### Ожидаемо:
Сотрудник не создан. Валидационное сообщение : "Должность содержит недопустимый символ"

См. Требования п.7 Поле Должность
![Qulix№2](https://user-images.githubusercontent.com/91781472/139144419-04ed1e99-feeb-4ff7-bc99-bf6a03156f2b.png)

**Comment by Svkarpova** [comment]
Не совсем корректный полученный результат, сохраняется не только значение одного поля, а вся запись.
