### ISSUE TITLE
Форма ввода/редактирования сотрудника: Сохранение невалидной комбинации символа пробел в поле Должность

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#17]
1. Перейти в [Cписок сотрудников]
2. Перейти в [Форма ввода сотрудника]
3. Заполнить все поля формы, кроме поля [Должность]
4. Заполнить поле [Должность] символами с несколькими пробелами
5. Сохранить запись

### Получено:
Значение поля сохранено

### Ожидаемо:
Запись не создана. Валидационное сообщение : "Должность содержит недопустимый символ"

См. Требования п.7 Поле Должность
![Qulix№4](https://user-images.githubusercontent.com/91781472/139145465-cbdc5737-8f9c-4e23-8357-487489b1ae92.png)

**Comment by Svkarpova** [comment]
Данный дефект и дефект №16, содержат одинаковый заголовок, но это два разных дефекта, подумай как можно переформулировать заголовки
