### ISSUE TITLE
Форма редактирования сотрудника: Несоответствие заголовка формы

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#19]
1. Перейти в [Cписок сотрудников]
2. Перейти в [Форма ввода сотрудника]
3. Сравнить заголовок формы с требованием

### Получено:
"Форма редактирования персоны"

### Ожидаемо:
"Форма редактирования сотрудника"

См. Требования п.7
![Qulix№8](https://user-images.githubusercontent.com/91781472/139147320-5568ffc9-d81d-403a-86ad-cfea6401f783.png)

**Comment by Svkarpova** [comment]
Из заголовка непонятно несоответствие заголовка формы чему? Аналогично в шагах в п.3
Лучше переформулировать заголовок "Неверное название формы"
