### ISSUE TITLE
Форма ввода задачи: Отсутствует поле [Идентификатор] 

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#20]
1. Перейти в [Список задач]
2. Перейти в [Форма ввода задачи]
3. Сравнить наличие полей

### Получено:
Отсутствует поле [Идентификатор]

### Ожидаемо:
Наличие поля [Идентификатор]

См. Требования п.6
![Qulix№9](https://user-images.githubusercontent.com/91781472/139313763-1b2ad12c-6c0f-4cfe-bce6-215a41509726.png)

**Comment by Svkarpova** [comment]
В заголовке лучше избегать частицы "не" и заменять словосочетание, например "Отсутствует поле "Идентификатор""
