### ISSUE TITLE
Форма ввода задачи: Неверное сообщение при отсутствии проектов

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#21]
### Предусловия:
Задачи отсутствуют

### Шаги:

1. Перейти в [Список задач]
2. Перейти в [Форма ввода задачи]
3. Сравнить текст сообщения

### Получено:
Сообщение "Нет ни одной записи."

### Ожидаемо:
Сообщение "Список пуст"

См. Требования дополнения п.6.2.6
![Qulix№10](https://user-images.githubusercontent.com/91781472/139314587-967f9517-1732-4bee-884d-13921cbc0edf.png)

**Comment by Svkarpova** [comment]
Данный дефект, уже есть для формы ввода проекта, одинаковый дефект для разных форм можно объединять в один
