### ISSUE TITLE
Форма ввода/редактирования задачи: Неверное валидационное сообщение поля [Работа]

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#27]
1. Перейти в [Список задач]
2. Перейти в [Форма ввода задачи]
3. Выполнить проверку для поля [Работа] цирфами и любыми символами с количеством от 1 до 9

### Получено:
Сообщение: "Работа содержит недопустимы символ"

### Ожидаемо:
Сообщение: "Неверное время"

См. Требования п.6 Поле Работа
![Qulix№24](https://user-images.githubusercontent.com/91781472/139319638-07524d17-d10e-4023-a806-031f53df8502.png)

**Comment by Svkarpova** [comment]
В шаге №3 нужно прописать конкретные шаги воспроизведения, формулировка "Выполнить проверку валидации для поля [Работа]" является довольно обобщенной, разработчик может не посмотреть в справку (или ее может не быть) и не будет знать какие символы являются валидными, какие нет
