### ISSUE TITLE
Форма редактирования задачи: Сброс отметки исполнителей при редактировании задачи 

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#28]
### Предусловие:
Имеется задача с назначенными исполнителями
### Шаги:

1. Перейти в [Список задач]
2. Перейти в [Форма редактирования задачи] через кнопку изменить 
3. Проверить состояние чекбоксов назначенных исполнителей

### Получено:
Чекбоксы первоначально назначенных исполнителей пусты

### Ожидаемо:
Чекбоксы первоначально назначенных исполнителей отмечены

См. Требования п.6 
![Часть 1](https://user-images.githubusercontent.com/91781472/139321066-64b4dc3a-e4a1-468d-a924-035b8d578c79.png)
![Часть 2](https://user-images.githubusercontent.com/91781472/139321070-0a1891a7-4906-4eaf-9adf-1681f2ad522e.png)

**Comment by Svkarpova** [comment]
Подумай как можно переформулировать заголовок.
Два раза в одном заголовке указывать форму излишне
