### ISSUE TITLE
Список проектов: Добавить функцию переноса длинных данных

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#3]
### Предусловия:
Имеется Проект, с данными максимальной длинны в каждом поле

### Шаги:

1.  Перейти в [Список проектов]
2.  Проверить отображение проекта имеющий данные максимальной длинны

### Получено:
Данные в колонке не переносятся и колонки имеют ширину наибольшего отображенного результата. Появляется горизонтальный скролл, что снижает удобство пользования.
 
### Ожидаемо:
Для удобства пользования реализовать функцию переноса длинных данных в колонке, что бы колонки суммарно имели ширину в пределах видимой области пользователя. Данные переносятся в соответствии с шириной колонки
![Qulix№40](https://user-images.githubusercontent.com/91781472/138763791-2d5e9755-487c-4508-8397-d90ff28ea7a8.png)

**Comment by Svkarpova** [comment]
Можно было не переводить дефект в improvement, а если ты перевел, то необходимо поменять заголовок и описание под improvement
