### ISSUE TITLE
Форма ввода проекта: Неверная валидация символов для поля [Название] 

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#33]
1. Перейти в [Список проектов]
2. Перейти в [Форма ввода проекта]
3. Выполнить проверку валидации сохранения символов ":?&%;@"для поля [Название]

### Получено:
Символы ?%&@ допустимы. 

### Ожидаемо:
Символы ?%&@ недопустимы. 

См. Требования п.5  Поле Название
![Qulix№26](https://user-images.githubusercontent.com/91781472/139331612-3b73a035-6c11-44a2-b8a4-870ed14b8692.png)
![+Qulix№28](https://user-images.githubusercontent.com/91781472/139331865-34313824-0c99-4c72-81a9-7235f3233153.png)

**Comment by Svkarpova** [comment]
Не содержательное название заголовка, проверки на максимальное кол-во символов и допустимое кол-во символов, проводятся отдельно, и дефекты должны быть заведены разные.
