### ISSUE TITLE
Форма ввода проекта: Сохранение нескольких символов пробела в поле "Название""Сокращенное название""Описание"

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#37]
1. Перейти в "Список задач"
2. Перейти в "Форма ввода задачи"
3. Заполнить поле "Название" пятью и более пробелами. Аналагично для  "Сокращенное название" и "Описание" 
4. Сохранить запись

### Получено:
Значение поля сохранено

### Ожидаемо:
Запись не создана. Валидационное сообщение : "Название не может содержать только символ пробела"
Аналагично для поля "Сокращенное название" и "Описание".
См. Требования п.5 Поле Название, Сокращенное название, Описание
![Qulix№39](https://user-images.githubusercontent.com/91781472/139336540-52557812-67a3-478a-92ee-885597130d79.png)

**Comment by Svkarpova** [comment]
- Не нужно было удалять слово "Сохранение", из заголовка не понятно в чем дефект.
- в шагах не обязательно прописывать заполнение всех перечисленных полей, можно для примера указать только одно поле, аналогично и в ожидаемом результате
