### ISSUE TITLE
Форма ввода проекта: Валидный символ "!" недопустим в поле "Описание"

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#38]
1. Перейти в [Список проектов]
2. Перейти в [Форма ввода проекта]
3. Заполнить поле [Описание] символами включая  "!"

### Получено:
Символ "!" недопустим

### Ожидаемо:
Символ "!" допустим

См. Требования п.5 Поле Описание
![Qulix№34](https://user-images.githubusercontent.com/91781472/139337435-f4b57da3-3a6a-4bf5-af64-88a339c5ad4a.png)

**Comment by Svkarpova** [comment]
Лучше немного переформулировать "Валидный символ "!" недопустим в поле "Описание""
