### ISSUE TITLE
Список проектов: Большой отступ слева при горизонтальном скролле

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#4]
### Предусловия:
Имеется "Список проектов" с горизонтальным скроллом

### Шаги:

1. Перейти в список проектов
2. Проверить расположение списка на странице

### Получено:
Большой отступ слева.

### Ожидаемо:
Отступ слева отсутствует.
![+Qulix№41](https://user-images.githubusercontent.com/91781472/138818509-24290587-0a1e-4c9f-a8b8-f27df063b965.png)

**Comment by Svkarpova** [comment]
- В заголовке отсутствует информация где большой отступ - справа/слева/сверху/снизу
- Для элементов лучше использовать такие кавычки "" а не такие []
