### ISSUE TITLE
Список проектов: Удаляются принадлежащие задачи при удалении проекта

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#5]
### Предусловия:
Имеется Проект, с назначенной задачей

### Шаги:

1. Перейти в список проектов
2. Удалить проект из списка проектов кнопкой Удалить
3. Проверить наличие задачи в Списке задач, которая принадлежала проекту

### Получено:
Удаляются принадлежащие задачи при удалении проекта

### Ожидаемо:
При удалении проекта принадлежащие задачи не удаляются. Сообщение "Удалите задачи принадлежащие данному проекту"

См. Требования п.2 [Список проектов].Удаление.; п.6.2.12 Уточнения требований

**Comment by Svkarpova** [comment]
- Лучше более конкретно отвечать на вопрос Что? не "Удаление принадлежащих задач при удалении проекта" а "Удаляются принадлежащие задачи при удалении проекта"
- Можно более кратко описать полученный и ожидаемый результат
