### ISSUE TITLE
Список проектов: Неверное сообщение при отсутствии проектов

### ISSUE THREAD

**Issue by AndreiGordey** [AndreiGordey/For-Intership-Qulix#7]
### Предусловия:
Проекты отсутствуют 

### Шаги:

1. Перейти в [Cписок проектов]
2. Сравнить текст сообщения

### Получено:
Сообщение "Нет ни одной записи."

### Ожидаемо:
Сообщение "Список пуст"

См. Требования дополнения  п.6.2.6 Отображение пустого "Списка проектов"
![+Qulix№13](https://user-images.githubusercontent.com/91781472/138954468-4f005749-76e4-4c3f-9801-9dfe3d993bee.png)

**Comment by Svkarpova** [comment]
В ссылке на требования нужно указывать не только номер пункта, но и название пункта
